plugins:
    - jekyll-feed
    - jekyll-remote-theme
    - jekyll-seo-tag
    - jekyll-sitemap
title: Noe Nieto
tagline: Mi sitio personal | Personal site
email: nnieto@noenieto.com
description: > 
  Noe Nieto es instructor de <a href="http://www.psicologiaholokinetica.org/">Psicología Holokinética</a>.
  Se graduó de ingeniero en Electrónica en el Instituto Tecnológico de Puebla y ahora cursa la
  Maestría en Ingeniería en la Universidad Autónoma de Baja California, en
  Mexicali, Baja California, México. Tiene más de 10 años de experiencia usando Linux todos los dias y
  es entusiasta del Software Libre
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://noenieto.com" # the base hostname & protocol for your site
author:
  name: Noe Nieto
  url: https://www.noenieto.com
  twitter: misaelnieto_a
twitter_username: misaelnieto_a
github_username:  misaelnieto
site: https://www.noenieto.com
webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234
  facebook: 1234
remote_theme: Holokinesis-Libros/bulma-clean-theme

permalink: /:year/:month/:day/:title.html
google_analytics: UA-34700214-1

# Disqus
disqus:
  shortname: noenieto
#SEO
twitter:
    username: misaelnieto_a
social:
  name: Noe Nieto
  links:
    - https://twitter.com/misaelnieto_a
    - https://www.facebook.com/nnietoarroyo
    - https://www.linkedin.com/in/noe-nieto-13529524
    - https://plus.google.com/u/0/105796039075975387109
    - https://github.com/misaelnieto
    - https://bitbucket.org/nnieto/
    - http://stackoverflow.com/users/667559/noe-nieto
prose:
    rooturl: '_posts'
    siteurl: "http://blog.noenieto.com/"
    relativeLinks: 'http://prose.github.io/starter/links.jsonp'
    ignore: ['Blog-Jekyll.sublime-project', 'Blog-Jekyll.sublime-workspace', 'CNAME']
    media: "media"

# Settings for the bulma-clean theme
paginate: 10
paginate_path: "/posts/:num"
footer_menu: footer
show_sidebar: false
favicon: /favicon.ico

exclude:
  - .github/
  - vercel_install.sh
  - vercel.json
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/