plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-timeago
    - jekyll-thumbnail-img
    - jekyll-toc
    - jekyll-autolinks
title: Noe Nieto
tagline: Mi sitio personal | Personal site
email: nnieto@noenieto.com
description: > 
  Hi! I'm an Electronics Engineer that's been happily working with software for the 
  last 20+ years.
  I've played different roles in the past, i.e., Frontend, Backend, Sysadmin and DBA.
  I like Free/Libre/Open Source Software. That's why I'd also like to define myself as a FLOSS generalist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://noenieto.com" # the base hostname & protocol for your site
permalink: /blog/:year/:title:output_ext
author:
  name: Noe Nieto
  description: Senior Software Engineer
  picture: /media/noe_nieto_480.jpg
  url: https://www.noenieto.com
  github: https://github.com/misaelnieto
  linkedin: https://www.linkedin.com/in/noe-nieto-13529524
  youtube: https://www.youtube.com/@nnietocs

twitter_username: misaelnieto_a
github_username:  misaelnieto
gh_sponsor: misaelnieto
site: https://www.noenieto.com
comments: true
# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234
#   facebook: 1234
# remote_theme: chrisrhymes/bulma-clean-theme@v1.0.0
theme: bulma-clean-theme
google_analytics: G-H2W0NR3S1W

# Disqus
disqus:
  shortname: noe-nieto.disqus.com
#SEO
twitter:
    username: misaelnieto_a
social:
  name: Noe Nieto
  links:
    - https://twitter.com/misaelnieto_a
    - https://www.facebook.com/nnietoarroyo
    - https://www.linkedin.com/in/noe-nieto-13529524
    - https://plus.google.com/u/0/105796039075975387109
    - https://github.com/misaelnieto
    - https://bitbucket.org/nnieto/
    - http://stackoverflow.com/users/667559/noe-nieto
prose:
    rooturl: '_posts'
    siteurl: "http://noenieto.com/"
    relativeLinks: 'http://prose.github.io/starter/links.jsonp'
    ignore: ['Blog-Jekyll.sublime-project', 'Blog-Jekyll.sublime-workspace', 'CNAME']
    media: "media"

# Settings for the bulma-clean theme
paginate: 10
paginate_path: "/blog/:num"
footer_menu: footer
show_sidebar: false
favicon: /favicon.ico

exclude:
  - .github/
  - vercel_install.sh
  - vercel.json
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .frontmatter/
  - frontmatter.json
  - watch.sh


# SEtttings for autolink plugin

autolinks:
  link_attr: 'target="_blank"'
  
force_theme: light

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      pagination:
        enabled: true
        permalink: "/blog/:num"
        sort_reverse: false
      author: "Noe Nieto"
