# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mosaico (Blog de Noe Nieto)
email: nnieto@noenieto.com
description: > # this means to ignore newlines until "baseurl:"
  Noe Nieto es instructor de Psicología Holokinética. Se graduó de ingeniero
  en Electrónica en el Instituto Tecnológico de Puebla y ahora cursa la
  Maestría en Ingeniería en la Universidad Autónoma de Baja California, en
  Mexicali, Baja California, México. Tiene más de 10 años de experiencia
  usando con Linux y es entusiasta del Software Libre
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: misaelnieto_a
github_username:  misaelnieto

# Build settings
markdown: kramdown
theme: minima
# lsi: true
permalink: /:year/:month/:day/:title.html
# Front-matter defaults
defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            layout: "post"
            author: "Noe Nieto"

# Google services
google_analytics: UA-34700214-1

# Disqus
disqus:
  shortname: noenieto