# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mosaico (Blog de Noe Nieto)
email: nnieto@noenieto.com
description: > # this means to ignore newlines until "baseurl:"
  Noe Nieto es instructor de <a href="http://www.psicologiaholokinetica.org/">Psicología Holokinética</a>.
  Se graduó de ingeniero en Electrónica en el Instituto Tecnológico de Puebla y ahora cursa la
  Maestría en Ingeniería en la Universidad Autónoma de Baja California, en
  Mexicali, Baja California, México. Tiene más de 10 años de experiencia usando Linux todos los dias y
  es entusiasta del Software Libre
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.noenieto.com" # the base hostname & protocol for your site
twitter_username: misaelnieto_a
github_username:  misaelnieto
site: https://www.noenieto.com

plugins:
    - jekyll-feed
    - jekyll-redirect-from
    - jekyll-remote-theme
    - jekyll-seo-tag
    - jekyll-sitemap

# Build settings
markdown: kramdown

theme: bulma-clean-theme
# remote_theme: gnarlacious/jekyll-theme-foundation
safe: false
# lsi: true
permalink: /:year/:month/:day/:title.html

# Front-matter defaults
defaults:
    -
        scope:
            path: ""
            type: posts
        values:
            layout: "post"
            author: "Noe Nieto"

# Google services
google_analytics: UA-34700214-1

# Disqus
disqus:
  shortname: noenieto
#SEO
twitter:
    username: misaelnieto_a
social:
  name: Noe Nieto
  links:
    - https://twitter.com/misaelnieto_a
    - https://www.facebook.com/nnietoarroyo
    - https://www.linkedin.com/in/noe-nieto-13529524
    - https://plus.google.com/u/0/105796039075975387109
    - https://github.com/misaelnieto
    - https://bitbucket.org/nnieto/
    - http://stackoverflow.com/users/667559/noe-nieto


prose:
    rooturl: '_posts'
    siteurl: "http://blog.noenieto.com/"
    relativeLinks: 'http://prose.github.io/starter/links.jsonp'
    ignore: ['Blog-Jekyll.sublime-project', 'Blog-Jekyll.sublime-workspace', 'CNAME']
    media: "media"

# Settings for the bulma-clean theme
paginate: 10
paginate_path: "/posts/:num"
footer_menu: footer
show_sidebar: false
favicon: /favicon.ico
