backend:
  name: git-gateway
  repo: misaelnieto/misaelnieto.github.io
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/img'
collections:
  - name: 'english_posts'
    label: 'Blog posts'
    folder: '_posts/'
    create: true
    filter: {field: "language", value: "en"}
    slug: '{{year}}/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: "Language", name: "language", widget: "select", options: ["en", "es"]}
      - { label: 'Layout', name: 'layout', widget: 'string', default: 'post' }
      - { label: 'Comments', name: 'comments', widget: 'hidden', default: 'true' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string'}
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Hero SVG', name: 'hero_svg', widget: 'image'}
      - { label: 'Card image', name: 'image', widget: 'image'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'spanish_posts'
    label: 'Blog en Español'
    folder: '_posts/'
    create: true
    filter: {field: "language", value: "es"}
    slug: '{{year}}/{{slug}}'
    editor:
      preview: true
    fields:
      - { label: "Language", name: "language", widget: "select", options: ["en", "es"]}
      - { label: 'Layout', name: 'layout', widget: 'string', default: 'post' }
      - { label: 'Comments', name: 'comments', widget: 'hidden', default: 'true' }
      - { label: "Titulo", name: "title", widget: "string"}
      - { label: 'Summary', name: 'summary', widget: 'string'}
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Hero SVG', name: 'hero_svg', widget: 'image'}
      - { label: 'Card image', name: 'image', widget: 'image'}
      - { label: "Contenido", name: "body", widget: "markdown"}
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: true
    files:
      - label: 'About Page'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'Noe - Human being' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Demos'
        name: 'demos'
        file: 'demos.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'Noe - Human being' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
